# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning_isolator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(833, 668)
        MainWindow.setMinimumSize(QtCore.QSize(833, 668))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_Label = QtWidgets.QLabel(self.centralwidget)
        self.title_Label.setGeometry(QtCore.QRect(30, 20, 721, 121))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.title_Label.setFont(font)
        self.title_Label.setObjectName("title_Label")
        self.logpath_Label = QtWidgets.QLabel(self.centralwidget)
        self.logpath_Label.setGeometry(QtCore.QRect(10, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(11)
        self.logpath_Label.setFont(font)
        self.logpath_Label.setObjectName("logpath_Label")
        self.compiler_Label = QtWidgets.QLabel(self.centralwidget)
        self.compiler_Label.setGeometry(QtCore.QRect(10, 230, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(11)
        self.compiler_Label.setFont(font)
        self.compiler_Label.setObjectName("compiler_Label")
        self.complierselect_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.complierselect_comboBox.setGeometry(QtCore.QRect(160, 230, 471, 31))
        self.complierselect_comboBox.setObjectName("complierselect_comboBox")
        self.compiler_Label_2 = QtWidgets.QLabel(self.centralwidget)
        self.compiler_Label_2.setGeometry(QtCore.QRect(10, 300, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(11)
        self.compiler_Label_2.setFont(font)
        self.compiler_Label_2.setObjectName("compiler_Label_2")
        self.gen_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.gen_pushButton.setGeometry(QtCore.QRect(30, 350, 221, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.gen_pushButton.setFont(font)
        self.gen_pushButton.setAutoDefault(True)
        self.gen_pushButton.setDefault(True)
        self.gen_pushButton.setObjectName("gen_pushButton")
        self.log_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.log_textEdit.setGeometry(QtCore.QRect(90, 160, 721, 31))
        self.log_textEdit.setObjectName("log_textEdit")
        self.save_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.save_textEdit.setGeometry(QtCore.QRect(100, 300, 711, 31))
        self.save_textEdit.setObjectName("save_textEdit")
        self.open_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_pushButton.setGeometry(QtCore.QRect(580, 350, 221, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.open_pushButton.setFont(font)
        self.open_pushButton.setObjectName("open_pushButton")
        self.update_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.update_textEdit.setGeometry(QtCore.QRect(10, 420, 811, 191))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(12)
        self.update_textEdit.setFont(font)
        self.update_textEdit.setObjectName("update_textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_Label.setText(_translate("MainWindow", " Warning Isolator v2.08"))
        self.logpath_Label.setText(_translate("MainWindow", "File Path:"))
        self.compiler_Label.setText(_translate("MainWindow", "Select Compiler:"))
        self.compiler_Label_2.setText(_translate("MainWindow", "Save Path:"))
        self.gen_pushButton.setText(_translate("MainWindow", "Generate"))
        self.log_textEdit.setPlaceholderText(_translate("MainWindow", "Please give the path of the log file..."))
        self.save_textEdit.setPlaceholderText(_translate("MainWindow", "Where do you want to save it???"))
        self.open_pushButton.setText(_translate("MainWindow", "Open File"))
